In [1]:
import pandas as pd
df=pd.read_csv(r"ratings_data.csv")

In [2]:
df

Combination  Occasion  Rating
0    1.jpg1.jpg1.jpg         1     0.1
1    1.jpg1.jpg1.jpg         2     0.1
2    1.jpg1.jpg1.jpg         3     0.2
3    1.jpg1.jpg2.jpg         1     8.0
4    1.jpg1.jpg2.jpg         2     7.0
..               ...       ...     ...
625  7.jpg6.jpg4.jpg         2     4.0
626  7.jpg6.jpg4.jpg         3     0.0
627  7.jpg6.jpg5.jpg         1     8.0
628  7.jpg6.jpg5.jpg         2     5.0
629  7.jpg6.jpg5.jpg         3     0.0

[630 rows x 3 columns]

In [3]:
comb=df['Combination']

In [4]:
store=[[]]
for k in comb:
    l1=[]
    j=0
    for i in range(len(k)):
        if(k[i]=='g'):
            l1.append(k[j:i+1])
            j=i+1
    store.append(l1)

In [5]:
store

[[],
 ['1.jpg', '1.jpg', '1.jpg'],
 ['1.jpg', '1.jpg', '1.jpg'],
 ['1.jpg', '1.jpg', '1.jpg'],
 ['1.jpg', '1.jpg', '2.jpg'],
 ['1.jpg', '1.jpg', '2.jpg'],
 ['1.jpg', '1.jpg', '2.jpg'],
 ['1.jpg', '1.jpg', '3.jpg'],
 ['1.jpg', '1.jpg', '3.jpg'],
 ['1.jpg', '1.jpg', '3.jpg'],
 ['1.jpg', '1.jpg', '4.jpg'],
 ['1.jpg', '1.jpg', '4.jpg'],
 ['1.jpg', '1.jpg', '4.jpg'],
 ['1.jpg', '1.jpg', '5.jpg'],
 ['1.jpg', '1.jpg', '5.jpg'],
 ['1.jpg', '1.jpg', '5.jpg'],
 ['1.jpg', '2.jpg', '1.jpg'],
 ['1.jpg', '2.jpg', '1.jpg'],
 ['1.jpg', '2.jpg', '1.jpg'],
 ['1.jpg', '2.jpg', '2.jpg'],
 ['1.jpg', '2.jpg', '2.jpg'],
 ['1.jpg', '2.jpg', '2.jpg'],
 ['1.jpg', '2.jpg', '3.jpg'],
 ['1.jpg', '2.jpg', '3.jpg'],
 ['1.jpg', '2.jpg', '3.jpg'],
 ['1.jpg', '2.jpg', '4.jpg'],
 ['1.jpg', '2.jpg', '4.jpg'],
 ['1.jpg', '2.jpg', '4.jpg'],
 ['1.jpg', '2.jpg', '5.jpg'],
 ['1.jpg', '2.jpg', '5.jpg'],
 ['1.jpg', '2.jpg', '5.jpg'],
 ['1.jpg', '3.jpg', '1.jpg'],
 ['1.jpg', '3.jpg', '1.jpg'],
 ['1.jpg', '3.jpg', '1.jpg'],
 ['1.

In [6]:
store.pop(0)

[]

In [7]:
store

[['1.jpg', '1.jpg', '1.jpg'],
 ['1.jpg', '1.jpg', '1.jpg'],
 ['1.jpg', '1.jpg', '1.jpg'],
 ['1.jpg', '1.jpg', '2.jpg'],
 ['1.jpg', '1.jpg', '2.jpg'],
 ['1.jpg', '1.jpg', '2.jpg'],
 ['1.jpg', '1.jpg', '3.jpg'],
 ['1.jpg', '1.jpg', '3.jpg'],
 ['1.jpg', '1.jpg', '3.jpg'],
 ['1.jpg', '1.jpg', '4.jpg'],
 ['1.jpg', '1.jpg', '4.jpg'],
 ['1.jpg', '1.jpg', '4.jpg'],
 ['1.jpg', '1.jpg', '5.jpg'],
 ['1.jpg', '1.jpg', '5.jpg'],
 ['1.jpg', '1.jpg', '5.jpg'],
 ['1.jpg', '2.jpg', '1.jpg'],
 ['1.jpg', '2.jpg', '1.jpg'],
 ['1.jpg', '2.jpg', '1.jpg'],
 ['1.jpg', '2.jpg', '2.jpg'],
 ['1.jpg', '2.jpg', '2.jpg'],
 ['1.jpg', '2.jpg', '2.jpg'],
 ['1.jpg', '2.jpg', '3.jpg'],
 ['1.jpg', '2.jpg', '3.jpg'],
 ['1.jpg', '2.jpg', '3.jpg'],
 ['1.jpg', '2.jpg', '4.jpg'],
 ['1.jpg', '2.jpg', '4.jpg'],
 ['1.jpg', '2.jpg', '4.jpg'],
 ['1.jpg', '2.jpg', '5.jpg'],
 ['1.jpg', '2.jpg', '5.jpg'],
 ['1.jpg', '2.jpg', '5.jpg'],
 ['1.jpg', '3.jpg', '1.jpg'],
 ['1.jpg', '3.jpg', '1.jpg'],
 ['1.jpg', '3.jpg', '1.jpg'],
 ['1.jpg',

In [8]:
paths= [r"D:\fcs_dataset\topwear", r"D:\fcs_dataset\bottomwear", r"D:\fcs_dataset\footwear"]
image_paths=[]
for i in range(len(store)):
    
    l=[]
    for j in range(len(store[i])):
        s=''
        s=s+paths[j]+"\\"+store[i][j]
        l.append(s)
    image_paths.append(l)

In [9]:
image_paths

[['D:\\fcs_dataset\\topwear\\1.jpg',
  'D:\\fcs_dataset\\bottomwear\\1.jpg',
  'D:\\fcs_dataset\\footwear\\1.jpg'],
 ['D:\\fcs_dataset\\topwear\\1.jpg',
  'D:\\fcs_dataset\\bottomwear\\1.jpg',
  'D:\\fcs_dataset\\footwear\\1.jpg'],
 ['D:\\fcs_dataset\\topwear\\1.jpg',
  'D:\\fcs_dataset\\bottomwear\\1.jpg',
  'D:\\fcs_dataset\\footwear\\1.jpg'],
 ['D:\\fcs_dataset\\topwear\\1.jpg',
  'D:\\fcs_dataset\\bottomwear\\1.jpg',
  'D:\\fcs_dataset\\footwear\\2.jpg'],
 ['D:\\fcs_dataset\\topwear\\1.jpg',
  'D:\\fcs_dataset\\bottomwear\\1.jpg',
  'D:\\fcs_dataset\\footwear\\2.jpg'],
 ['D:\\fcs_dataset\\topwear\\1.jpg',
  'D:\\fcs_dataset\\bottomwear\\1.jpg',
  'D:\\fcs_dataset\\footwear\\2.jpg'],
 ['D:\\fcs_dataset\\topwear\\1.jpg',
  'D:\\fcs_dataset\\bottomwear\\1.jpg',
  'D:\\fcs_dataset\\footwear\\3.jpg'],
 ['D:\\fcs_dataset\\topwear\\1.jpg',
  'D:\\fcs_dataset\\bottomwear\\1.jpg',
  'D:\\fcs_dataset\\footwear\\3.jpg'],
 ['D:\\fcs_dataset\\topwear\\1.jpg',
  'D:\\fcs_dataset\\bottomwear\\1.j

In [10]:
import cv2


pixels_x1=[]
pixels_x2=[]
pixels_x3=[]
for i in image_paths:
    for j in range(len(i)):
        img=cv2.imread(i[j])
        img=cv2.resize(img,(128,128))
        if(j==0):
            pixels_x1.append(img)
        elif(j==1):
            pixels_x2.append(img)
        else:
            pixels_x3.append(img)
            

In [12]:
import numpy as np
np.shape(pixels_x1[0])

(128, 128, 3)

In [13]:
one_hot_encoded = pd.get_dummies(df['Occasion'])

In [14]:
one_hot_encoded

1  2  3
0    1  0  0
1    0  1  0
2    0  0  1
3    1  0  0
4    0  1  0
..  .. .. ..
625  0  1  0
626  0  0  1
627  1  0  0
628  0  1  0
629  0  0  1

[630 rows x 3 columns]

In [15]:
df['Occasion']

0      1
1      2
2      3
3      1
4      2
      ..
625    2
626    3
627    1
628    2
629    3
Name: Occasion, Length: 630, dtype: int64

In [16]:
import numpy as np
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
label_encoder = LabelEncoder()

# Fit and transform the categorical values
encoded_categories = label_encoder.fit_transform(df['Occasion'])

# Convert encoded categories to one-hot encoded format
one_hot_encoded = to_categorical(encoded_categories)

print(one_hot_encoded)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
occasion =np.array(one_hot_encoded)

In [18]:
rating = np.array(df['Rating'])/10

In [21]:
occasion.shape

(630, 3)

In [24]:
pixels_x1=np.array(pixels_x1)
pixels_x2=np.array(pixels_x2)
pixels_x3=np.array(pixels_x3)

In [25]:
pixels_x1.shape

(630, 128, 128, 3)

In [26]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Concatenate, BatchNormalization, Dropout

# Define input shapes
image_input_shape = (128, 128, 3)  # Adjust based on your image dimensions
num_occasions = 3  # Number of occasion categories

# Create input layers for images
image_input1 = Input(shape=image_input_shape, name='image_input1')
image_input2 = Input(shape=image_input_shape, name='image_input2')
image_input3 = Input(shape=image_input_shape, name='image_input3')

# Define CNN layers for image inputs
conv1_1 = Conv2D(32, (3, 3), activation='relu', padding='same')(image_input1)
maxpool1_1 = MaxPooling2D(pool_size=(2, 2))(conv1_1)

conv1_2 = Conv2D(32, (3, 3), activation='relu', padding='same')(image_input2)
maxpool1_2 = MaxPooling2D(pool_size=(2, 2))(conv1_2)

conv1_3 = Conv2D(32, (3, 3), activation='relu', padding='same')(image_input3)
maxpool1_3 = MaxPooling2D(pool_size=(2, 2))(conv1_3)

flatten1_1 = Flatten()(maxpool1_1)
flatten1_2 = Flatten()(maxpool1_2)
flatten1_3 = Flatten()(maxpool1_3)

# Concatenate flattened image features
concatenated_images = Concatenate()([flatten1_1, flatten1_2, flatten1_3])

# Define categorical input
occasion_input = Input(shape=(num_occasions,), name='occasion_input')

# Concatenate image features and categorical input
combined_input = Concatenate()([concatenated_images, occasion_input])

# Fully connected layers with BatchNormalization and Dropout
dense1 = Dense(256, activation='relu')(combined_input)
batchnorm1 = BatchNormalization()(dense1)
dropout1 = Dropout(0.5)(batchnorm1)

dense2 = Dense(128, activation='relu')(dropout1)
batchnorm2 = BatchNormalization()(dense2)
dropout2 = Dropout(0.5)(batchnorm2)

output = Dense(1, activation='sigmoid', name='output')(dropout2)  # Linear activation for a regression task

# Create the model
model = Model(inputs=[image_input1, image_input2, image_input3, occasion_input], outputs=output)

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')  # Using mean squared error for regression

# Print model summary
model.summary()


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 image_input1 (InputLayer)      [(None, 128, 128, 3  0           []                               
                                )]                                                                
                                                                                                  
 image_input2 (InputLayer)      [(None, 128, 128, 3  0           []                               
                                )]                                                                
                                                                                                  
 image_input3 (InputLayer)      [(None, 128, 128, 3  0           []                               
                                )]                                                            

In [33]:
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D, Flatten, Dense, Concatenate
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam 
 

from tensorflow.keras.optimizers import SGD
# Compile the model
model.compile(optimizer=SGD(learning_rate=0.001), loss='mean_squared_error', metrics=['mae'])






In [34]:
pixels_x1.shape

(630, 32, 32, 3)

In [31]:
# Train the model
model.fit(
     [pixels_x1, pixels_x2,pixels_x3,occasion],
    rating,
    batch_size=10,
    epochs=10
   )

Epoch 1/10
63/63 [==============================] - 99s 2s/step - loss: 0.1276
Epoch 2/10
63/63 [==============================] - 97s 2s/step - loss: 0.1182
Epoch 3/10
63/63 [==============================] - 98s 2s/step - loss: 0.1168
Epoch 4/10
63/63 [==============================] - 98s 2s/step - loss: 0.1127
Epoch 5/10
63/63 [==============================] - 100s 2s/step - loss: 0.1133
Epoch 6/10
63/63 [==============================] - 104s 2s/step - loss: 0.1045
Epoch 7/10
63/63 [==============================] - 104s 2s/step - loss: 0.1019
Epoch 8/10
63/63 [==============================] - 102s 2s/step - loss: 0.0957
Epoch 9/10
63/63 [==============================] - 103s 2s/step - loss: 0.0952
Epoch 10/10
63/63 [==============================] - 103s 2s/step - loss: 0.0919


In [32]:
model.save("fashion-reccomendation1.h5")

In [38]:

l=[pixels_x1[0][np.newaxis, :],pixels_x2[0][np.newaxis, :],pixels_x3[0][np.newaxis, :],np.array([[1, 0, 0]])]
model.predict(l)

1/1 [==============================] - 7s 7s/step


array([[0.5498345]], dtype=float32)

In [27]:
occasion

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [37]:
np.array(occasion[0])

array([1., 0., 0.], dtype=float32)

In [40]:
pixels_x1[0][np.newaxis, :].shape

(1, 128, 128, 3)

In [44]:
k=np.array([[1, 0, 0]])

In [45]:
k.shape

(1, 3)

In [8]:
import cv2

Tensorflow version: 2.12.0


In [9]:
img1=cv2.imread(r'D:\\fcs_dataset\\topwear\\5.jpg')
img2=cv2.imread(r'D:\\fcs_dataset\\bottomwear\\2.jpg')
img3=cv2.imread(r'D:\\fcs_dataset\\footwear\\2.jpg')

In [10]:
img1=np.resize(img1,(1,128,128,3))
img2=np.resize(img2,(1,128,128,3))
img3=np.resize(img3,(1,128,128,3))

In [13]:
model=tf.keras.models.load_model('fashion-reccomendation1.h5')

In [14]:
model.predict([img1,img2,img3,np.array([[0,1,0]])])

1/1 [==============================] - 14s 14s/step


array([[0.7658222]], dtype=float32)

In [1]:
import numpy as np
occ=np.array([[0,1,0]])

In [2]:
occ.shape

(1, 3)

In [15]:
img1

array([[[[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        ...,

        [[233, 209, 197],
         [234, 210, 198],
         [223, 201, 189],
         ...,
         [234, 215, 202],
         [255, 246, 243],
         [253, 254, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
         [255, 255, 255],
         [255, 255, 255]],

        [[255, 255, 255],
         [255, 255, 255],
         [255, 255, 255],
         ...,
         [255, 255, 255],
        